#ifndef TIM_CFG_H
#define TIM_CFG_H

#define TIM0_MODE        TIM0_NORMAL_MODE
#define TIM0_PRESCALLER  TIM0_PRESCALLER_8

#define TIM1_MODE        TIM0_NORMAL_MODE
#define TIM1_PRESCALLER  TIM0_PRESCALLER_8

#define TIM2_MODE        TIM0_CTC_MODE
#define TIM2_PRESCALLER  TIM0_PRESCALLER_8

#endif 